spring:
  application:
    name: service-registry
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      wait-time-in-ms-when-sync-empty: 0
      eviction-interval-timer-in-ms: 30000
      response-cache-update-interval-ms: 3000
      enable-self-preservation: true
      max-in-memory-instances-per-app: 1000
      renewal-percent-threshold: 0.85
