spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wliamp/configurations.git
          username: wliamp
          default-label: main
          search-paths:
            - common
            - apps

server:
  port: 8888
